site_tracker/users/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user

from .forms import LoginForm, RegistrationForm
from .models import User

users = Blueprint('users', __name__)


@users.route('/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.user)
        flash("Logged in successfully.")
        # There's a subtle security hole in this code, which we will be fixing in our next article.
        # Don't use this exact pattern in anything important.
        return redirect(request.args.get("next") or url_for("tracker.index"))
    return render_template('users/login.html', form=form)


@users.route('/register/', methods=('GET', 'POST'))
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.create(**form.data)
        login_user(user)
        return redirect(url_for('tracker.index'))
    return render_template('users/register.html', form=form)


@users.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('tracker.index'))

site_tracker/templates/data_list.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View {{ super() }}{% endblock %}
{% block content %}
{{ super() }}
<table>
{{ tables.render(data) }}
</table>
{% endblock content %}

site_tracker/templates/index.html
{% extends "layout.html" %}
{% block title %}Welcome to Site Tracker!{% endblock %}
{% block content %}
{{ super() }}
<p>Welcome stranger! Don't be shy, just try by <a href="{{url_for('users.register')}}">register with us</a>.
If you have been here before then why not <a href="{{url_for('users.login')}}">sign in</a>?</p>
{% endblock content %}

site_tracker/templates/layout.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ title }}{% endblock %}</title>
</head>
<body>
<header>
<h1>{{ self.title() }}</h1>
<nav>
<ul>
<li><a href="/">Home</a></li>
<li><a href="/sites">Sites</a></li>
<li>
	{% if current_user.is_anonymous() %}
	<a href="{{url_for('users.register')}}">Register</a> / <a href="{{url_for('users.login')}}">Log In</a>
	{% else %}
	Logged in as {{current_user.name}} <a href="{{url_for('users.logout')}}">Logout</a>
	{% endif %}
</li>
</ul>
</nav>
</header>
{% set messages = get_flashed_messages() %}
{% if messages %}
<section>
	{% for message in messages %}
	<p>{{ message }}</p>
	{% endfor %}
</section>
{% endif %}
<section>
{% block content %}{% endblock %}
</section>
<footer>
<p>#{{ constants.RIGHTS }}</p>
</footer>
</body>
</html>

site_tracker/templates/validation_error.html
{% extends "layout.html" %}
{% import "helpers/forms.html" as forms %}
{% block title %}Validation Error - Flask Tracking{% endblock %}
{% block content %}
{{ super() }}
<p>An error occured, please correct any mistakes and try again.</p>
<ul>
{% for field in form if field.errors %}
<li>{{ field.label }}:
    <ul>
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
    </ul>
</li>
{% endfor %}
</ul>
<form method="POST">
<fieldset>
<legend>Data</legend>
{{ forms.render(form) }}
<p><input type="Submit" value="Save Data"></p>
</fieldset>
</form>
{% endblock content %}